newly uploaded artwork now displays in search, have removed lazy load…
nikstojkov/AllofYou pull request #147
Opened 2023-03-15 21:28 UTC by nikstojkov

…ing logic

2023-03-15 22:21 UTC, sulphite requested changes

2023-03-15 22:21 UTC, sulphite commented on app/views/shared/_artwork_result.html.erb
> +      <%= cl_image_tag artwork.photo.key %>
yooooooo ok so the fix is if you change it to `<%= image_tag "blobload.gif", class: "lazy", data: {src: cl_image_path(artwork.photo.key), lazy_loader_target: "image" } %>`

2023-03-15 22:21 UTC, sulphite commented on app/views/shared/_artwork_result.html.erb
> +      <%= image_tag artwork.image_url %>
also change this one back

2023-03-15 22:25 UTC, nikstojkov commented on app/views/shared/_artwork_result.html.erb
> +      <%= cl_image_tag artwork.photo.key %>
God damn 😂 i tried so many combinations of adding the cl_image bit into the SRC... Asides from that one...

Figured it was something very similar to our MAPBOX_API_KEY fun.

2023-03-16 09:28 UTC, sulphite approved these changes

2023-03-16 09:33 UTC, merged