Appication controller (probably wrong)
nikstojkov/AllofYou pull request #16
Opened 2023-03-07 17:56 UTC by nikstojkov

2023-03-07 18:01 UTC, JDS478 commented on app/controllers/applications_controller.rb
> +    @application = Application.find(params[:application_id])
Maybe add to the before_action instead?

2023-03-07 18:01 UTC, Nick-ODonoghue reviewed
Think before action should only be for show edit update and destroy actions.

Also def delete - Should this be def destroy?

2023-03-07 18:55 UTC, nikstojkov commented on app/controllers/applications_controller.rb
> +  before_action :set_opportunity, only: [:new]
Add create

2023-03-07 18:57 UTC, nikstojkov commented on app/controllers/applications_controller.rb
> +  def create
Application.user = @user/current_user

2023-03-07 19:05 UTC, nikstojkov commented on app/controllers/applications_controller.rb
> +    @application = Application.find(params[:application_id])
Just params[:I'd]

2023-03-07 19:06 UTC, nikstojkov commented on app/controllers/applications_controller.rb
> +    @review.destroy
@application.destroy.... not review!!!

2023-03-07 21:28 UTC, sulphite requested changes

2023-03-07 23:01 UTC, nikstojkov commented on app/controllers/artworks_controller.rb
>      artwork.save
im confused now. line 14?

2023-03-07 23:06 UTC, sulphite commented on app/controllers/artworks_controller.rb
>      artwork.save
line 13, right after this you have `if artwork.save`

2023-03-07 23:34 UTC, nikstojkov commented on app/controllers/artworks_controller.rb
>      artwork.save
Gotcha, i think in my head it was "try to save" -> "if saved do this"... There's the same code in the opportunities controller.

2023-03-08 11:08 UTC, sulphite approved these changes
looks good

2023-03-08 11:09 UTC, merged